name: test

on: push

jobs:
  lint:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install pylint
      run: |
        pip install pylint
    - name: Pylint
      run: |
        pylint **/*.py

